version: "3.9"

services:

  mongo:
    image: mongo
    container_name: renyou_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: renyou_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/renyou

  frontend:
    build: ./frontend
    container_name: renyou_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: